"use client";
import {useState,useEffect} from "react";
import {useSession} from "next-auth/react";
import Link from "next/link";
import {ShieldCheck,Bell,UserRound,MessageSquare} from "lucide-react";
import {getApiUrl} from "@/lib/api-config";
import {Heading,Panel,Empty} from "../../components/qaytarme/ui";
export default function Settings(){
 const {data:session,status}=useSession(),[form,setForm]=useState({matches:true,messages:true,handover:true,system:true}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!session?.user?.accessToken)return;const c=new AbortController();fetch(getApiUrl("users/notification-preferences"),{signal:c.signal,headers:{Authorization:"Bearer "+session.user.accessToken}}).then(async r=>{if(!r.ok)throw Error("Sozlamalarni yuklab bo‘lmadi.");return r.json();}).then(data=>{setForm(data);setLoaded(true);}).catch(e=>{if(e.name!=="AbortError")setMessage(e.message);});return()=>c.abort();},[session]);
 async function save(e){e.preventDefault();setBusy(true);try{const r=await fetch(getApiUrl("users/notification-preferences"),{method:"PUT",headers:{Authorization:"Bearer "+session.user.accessToken,"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok)throw Error("Sozlamalarni saqlab bo‘lmadi.");setMessage("Bildirishnoma sozlamalari saqlandi.");}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <><Heading title="Sozlamalar" text="Bildirishnomalar va shaxsiy hisobingizni boshqaring."/>{!session&&status!=="loading"?<Panel><Empty title="Sozlamalarni boshqarish uchun kiring"><Link className="qm-btn qm-btn-dark" href="/login?callbackUrl=%2Fdesktop%2Fsettings">Hisobga kirish</Link></Empty></Panel>:<div className="qm-admin-grid"><Panel title="Bildirishnoma sozlamalari"><form className="qm-form" onSubmit={save}>{message&&<div className="qm-notice" role="status">{message}</div>}<p className="qm-detail-description">Ilova ichida qaysi bildirishnomalar ko‘rinishini tanlang.</p>{[["matches","Yangi mosliklar"],["messages","Xabarlar"],["handover","Topshirish va qabul qilish"],["system","E’lon holati va tizim xabarlari"]].map(([key,label])=><label key={key} className="qm-check"><input type="checkbox" checked={form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/><span>{label}</span></label>)}<button className="qm-btn qm-btn-dark" disabled={!loaded||busy}>{busy?"Saqlanmoqda…":"O‘zgarishlarni saqlash"}</button></form></Panel><div className="qm-admin-side"><Panel title="Profil va maxfiylik"><div className="qm-panel-body"><p className="qm-detail-description">Aloqa ma’lumotlaringiz ochiq e’lonlarda yashiriladi. Shaxsiy ma’lumotlarni profil sahifasida boshqaring.</p><Link className="qm-btn" href="/desktop/profile"><UserRound size={14}/>Profilni tahrirlash</Link></div></Panel><Panel title="Yordam"><div className="qm-panel-body"><p className="qm-detail-description">Qidirish, e’lon berish va buyumni xavfsiz qaytarish bo‘yicha ma’lumot oling.</p><Link className="qm-btn" href="/desktop/about">Qanday ishlaydi →</Link></div></Panel></div></div>}</>;
}

