"use client";
import {useState,useEffect} from "react";
import {Heading,Panel,Badge} from "../../components/qaytarme/ui";
import {useAdminData,adminRequest} from "../../components/qaytarme/admin-api";
import {State,Notice} from "../../components/qaytarme/AdminShared";
export default function Settings(){
 const {data,loading,error,refresh,token}=useAdminData("settings"),[form,setForm]=useState({moderateWeb:false,moderateTelegram:true,imageDisplayMode:"sensitive"}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(data)setForm({moderateWeb:!!data.moderateWeb,moderateTelegram:!!data.moderateTelegram,imageDisplayMode:["sensitive","blurred","normal"].includes(data.imageDisplayMode)?data.imageDisplayMode:"sensitive"});},[data]);
 async function save(e){e.preventDefault();setBusy(true);try{await adminRequest("settings",token,form);setMessage("Sozlamalar saqlandi. Rasm ko‘rinishi barcha e’lonlarga qo‘llanadi.");await refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <><Heading title="Sozlamalar" text="E’lonlar moderatsiyasi va integratsiyalar holati."/><State {...{loading,error,refresh}}/><Notice message={message}/><div className="qm-admin-grid"><Panel title="E’lon va moderatsiya"><form className="qm-form" onSubmit={save}><label className="qm-check"><input type="checkbox" checked={form.moderateWeb} onChange={e=>setForm({...form,moderateWeb:e.target.checked})}/><span>Foydalanuvchi e’lonlari moderatsiyadan o‘tsin</span></label><label className="qm-check"><input type="checkbox" checked={form.moderateTelegram} onChange={e=>setForm({...form,moderateTelegram:e.target.checked})}/><span>Telegramdan import qilingan e’lonlar moderatsiyaga yuborilsin</span></label><div className="qm-field"><label htmlFor="admin-image-display"><strong>E’lon rasmlari</strong></label><select id="admin-image-display" value={form.imageDisplayMode} onChange={e=>setForm({...form,imageDisplayMode:e.target.value})}><option value="sensitive">Maxfiy rasmlarni xiralashtirish (standart)</option><option value="blurred">Barcha rasmlarni xiralashtirish</option><option value="normal">Barcha rasmlarni asl holida ko‘rsatish</option></select><p className="qm-muted">Bu sozlama e’lonlar ro‘yxati, xarita, mosliklar va tafsilotlarda ishlaydi. Hujjat, bank karta va avtomobil raqami kabi maxfiy rasmlar standart holatda xiralashtiriladi. “Asl holida” tanlansa, barcha rasmlar ochiq ko‘rinadi.</p></div><p className="qm-notice">Rasm sozlamasi barcha e’lonlarga ta’sir qiladi; moderatsiya sozlamalari yangi e’lonlarga qo‘llanadi.</p><button className="qm-btn qm-btn-dark" disabled={busy||loading}>{busy?"Saqlanmoqda…":"O‘zgarishlarni saqlash"}</button></form></Panel><Panel title="Integratsiyalar va tizim"><div className="qm-status-list">{[["mongo","MongoDB"],["telegram","Telegram userbot"],["ai","Matn va rasm tahlili"],["images","Rasmlar xizmati"],["email","Email xizmati"]].map(([k,label])=><div key={k}><span>{label}</span><Badge tone={data?.integrations?.[k]?"success":"warning"}>{data?.integrations?.[k]?(k==="mongo"||k==="telegram"?"Ulangan":"Kalit sozlangan"):"Sozlash kerak"}</Badge></div>)}</div><p className="qm-notice" style={{margin:16}}>Maxfiy API kalitlari va Telegram session faqat serverdagi muhit faylida boshqariladi.</p></Panel></div></>;
}

