"use client";
import {useEffect,useState,Suspense} from "react";
import Link from "next/link";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {Bookmark,ArrowUpRight,SlidersHorizontal,RotateCcw,Send,ShieldCheck,Link2,ChevronLeft,ChevronRight} from "lucide-react";
import {buildArizaListUrl} from "@/lib/ariza-api";
import {categories,Heading,Panel,Empty,ItemImage,Badge,Source,MapPin,Search,dateOf,ArrowRight} from "../components/qaytarme/ui";
import {ItemCard} from "../components/qaytarme/ItemCard";

function Home(){
 const pathname=usePathname(),params=useSearchParams(),router=useRouter(),home=pathname==="/desktop";
 const [q,setQ]=useState(params.get("q")||""),[search,setSearch]=useState(params.get("q")||""),[status,setStatus]=useState("all"),[category,setCategory]=useState(params.get("category")||"all"),[source,setSource]=useState("all"),[region,setRegion]=useState(""),[page,setPage]=useState(1);
 const [data,setData]=useState({arizalar:[],total:0}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[reload,setReload]=useState(0);
 useEffect(()=>{setSearch(params.get("q")||"");setQ(params.get("q")||"");setCategory(params.get("category")||"all");setPage(1);},[params]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError("");fetch(buildArizaListUrl({page,limit:12,search,status,category,source,region}),{signal:c.signal}).then(async r=>{if(!r.ok)throw Error("E’lonlarni yuklab bo‘lmadi. Qayta urinib ko‘ring.");return r.json();}).then(setData).catch(e=>{if(e.name!=="AbortError")setError(e.message === "Failed to fetch" ? "Server bilan bog‘lanib bo‘lmadi. Birozdan so‘ng qayta urinib ko‘ring." : e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[page,search,status,category,source,region,reload]);
 const reset=()=>{setStatus("all");setCategory("all");setSource("all");setRegion("");setSearch("");setQ("");setPage(1);router.replace(pathname);};
 return <div>
 <Heading eyebrow={home?"TOPING. BOG‘LANING. QAYTARING.":"BARCHA MANBALAR BIR JOYDA"} title={home?"Yo‘qolgan buyumlar, topilgan umidlar":"E’lonlar"} text={home?"Telegram kanallari va Buyum Qidiruv’dagi e’lonlar orasidan buyumingizni izlang.":"Yo‘qolgan va topilgan buyumlarni manba, hudud va turiga qarab qidiring."}><Link className="qm-btn" href="/desktop/map"><MapPin size={15}/>Xaritada ko‘rish</Link><Link className="qm-btn qm-btn-dark" href="/desktop/add"><span>＋</span>E’lon berish</Link></Heading>
 {home && <div className="qm-intro"><div className="qm-intro-copy"><Badge><Send size={12}/>Telegram + Buyum Qidiruv</Badge><h2>Buyumingiz boshqa<br/>kanalda topilgan bo‘lishi mumkin.</h2><p>Bitta qidiruv bilan turli manbalardagi e’lonlarni ko‘ring.<br/>Buyumingiz haqida e’lon bering — mosliklarni birga izlaymiz.</p><Link href="/desktop/add?type=lost" className="qm-text-link">Buyumimni yo‘qotdim <ArrowRight size={15}/></Link></div><div className="qm-flow"><div><span><Send size={19}/></span><strong>E’lonlar yig‘iladi</strong><small>Ulangan Telegram kanallaridan</small></div><i/><div><span><Link2 size={19}/></span><strong>Mosliklar izlanadi</strong><small>Buyum, tavsif, joy va sana bo‘yicha</small></div><i/><div><span><ShieldCheck size={19}/></span><strong>Egasiga qaytadi</strong><small>Ikki tomonning tasdig‘i bilan</small></div></div></div>}
 <Panel className="qm-search-panel">
 <form onSubmit={e=>{e.preventDefault();setSearch(q);setPage(1);}} className="qm-search-row"><label className="qm-search-field"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nimani qidiryapsiz? Masalan: qora ryukzak" aria-label="Buyum nomi"/></label><label className="qm-region"><MapPin size={17}/><select aria-label="Hudud" value={region} onChange={e=>{setRegion(e.target.value);setPage(1);}}><option value="">Barcha hududlar</option>{["Toshkent","Samarqand","Buxoro","Andijon","Farg‘ona","Namangan","Jizzax","Navoiy","Qashqadaryo","Surxondaryo","Sirdaryo","Xorazm","Qoraqalpog‘iston"].map(v=><option key={v}>{v}</option>)}</select></label><button className="qm-btn qm-btn-dark">Qidirish <ArrowRight size={15}/></button></form>
 <div className="qm-filter-row"><div className="qm-tabs">{[["all","Barchasi"],["lost","Yo‘qolgan buyumlar"],["found","Topilgan buyumlar"]].map(([id,label])=><button key={id} className={status===id?"active":""} onClick={()=>{setStatus(id);setPage(1);}}>{label}</button>)}</div><select aria-label="Manba" value={source} onChange={e=>{setSource(e.target.value);setPage(1);}}><option value="all">Barcha manbalar</option><option value="telegram">Telegram</option><option value="web">Saytdagi e’lonlar</option></select><button className="qm-clear" onClick={reset}><RotateCcw size={13}/>Tozalash</button></div>
 </Panel>
 <div className="qm-category-row">{categories.map(([id,label,Icon])=><button key={id} className={category===id?"active":""} onClick={()=>{setCategory(id);setPage(1);}}><Icon size={15}/>{label}</button>)}</div>
 <div className="qm-section-title"><h2>{search?"Qidiruv natijalari":"So‘nggi e’lonlar"}<small>{loading?"Yuklanmoqda…":data.total+" ta e’lon"}</small></h2><span><SlidersHorizontal size={14}/> Eng yangi</span></div>
 {error?<Panel><Empty title="Ulanishda xatolik" text={error}><button className="qm-btn" onClick={()=>setReload(v=>v+1)}>Qayta urinish</button></Empty></Panel>:loading?<div className="qm-card-grid">{Array.from({length:8},(_,i)=><div key={i} className="qm-skeleton"/>)}</div>:data.arizalar?.length?<div className="qm-card-grid">{data.arizalar.map(item=><ItemCard key={item._id} item={item}/>)}</div>:<Panel><Empty title="E’lon topilmadi" text="Boshqa so‘z bilan qidiring yoki filtrlarni o‘zgartiring."><button className="qm-btn" onClick={reset}>Filtrlarni tozalash</button><Link className="qm-btn qm-btn-dark" href="/desktop/add">E’lon berish</Link></Empty></Panel>}
 <div className="qm-pagination"><span>{data.total>0?((page-1)*12+1)+"–"+Math.min(page*12,data.total)+" / "+data.total:"0 ta e’lon"}</span><div><button className="qm-icon-btn" disabled={page===1||loading} aria-label="Oldingi sahifa" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><Badge>{page}</Badge><button className="qm-icon-btn" disabled={!data.hasMore||loading} aria-label="Keyingi sahifa" onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div>
 <div className="qm-help-strip"><ShieldCheck size={22}/><div><strong>Buyum egasini ehtiyotkorlik bilan aniqlang</strong><p>Hujjat yoki karta raqamini ommaga oshkor qilmang. Buyumdagi maxsus belgilarni egasidan so‘rang.</p></div><Link href="/desktop/about">Qanday ishlaydi <ArrowUpRight size={14}/></Link></div>
 </div>;
}
export default function HomePage(){return <Suspense fallback={<div className="qm-loading">Yuklanmoqda…</div>}><Home/></Suspense>;}

