"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {useSession,signOut} from "next-auth/react";
import {useState} from "react";
import {Search,LayoutDashboard,ShieldCheck,ClipboardList,TriangleAlert,Users,Folder,Send,FileClock,Settings,LogOut,ArrowUpRight,UserRound,Menu,X} from "lucide-react";
import {Empty} from "../components/qaytarme/ui";
const menu=[["/admin","Boshqaruv markazi",LayoutDashboard],["/admin/moderation","Moderatsiya",ShieldCheck],["/admin/items","E’lonlar",ClipboardList],["/admin/reports","Shikoyatlar",TriangleAlert],["/admin/users","Foydalanuvchilar",Users],["/admin/categories","Kategoriyalar",Folder],["/admin/telegram-channels","Telegram manbalari",Send],["/admin/audit","Audit jurnali",FileClock],["/admin/settings","Sozlamalar",Settings]];
export default function AdminLayout({children}){
 const {data:session,status}=useSession(),pathname=usePathname(),[open,setOpen]=useState(false),[query,setQuery]=useState(""),router=useRouter();
 if(status==="loading")return <div className="qm-loading">Hisob tekshirilmoqda…</div>;
 if(session?.user?.role!=="admin")return <div className="qm-app"><Empty title="Boshqaruv paneliga kirish" text="Bu sahifa administratorlar uchun. Administrator hisobingiz bilan kiring."><Link href="/login?callbackUrl=%2Fadmin" className="qm-btn qm-btn-dark">Hisobga kirish</Link><Link className="qm-btn" href="/desktop">Bosh sahifa</Link></Empty></div>;
 return <div className="qm-app qm-admin">{open&&<button className="qm-scrim" aria-label="Menyuni yopish" onClick={()=>setOpen(false)}/>}<aside className={"qm-sidebar "+(open?"is-open":"")}><Link className="qm-brand" href="/admin"><span className="qm-brand-mark"><Search size={23}/></span><span><strong>Buyum Qidiruv <span style={{fontWeight:400,color:"#b0b4bf",fontSize:12}}>Admin</span></strong><small>Boshqaruv markazi</small></span></Link><button className="qm-mobile-close" onClick={()=>setOpen(false)} aria-label="Menyuni yopish"><X size={18}/></button><nav>{menu.map(([href,label,Icon])=><Link key={href} href={href} className={pathname===href||href!=="/admin"&&pathname.startsWith(href+"/")?"active":""} onClick={()=>setOpen(false)}><Icon size={16}/>{label}</Link>)}</nav><div className="qm-sidebar-bottom"><Link href="/desktop"><ArrowUpRight size={16}/>Saytga o‘tish</Link><button onClick={()=>signOut({callbackUrl:"/"})}><LogOut size={16}/>Chiqish</button></div><div className="qm-sidebar-note"><UserRound size={18}/><span>{session.user.name}<br/>Administrator</span></div></aside><div className="qm-main"><header className="qm-topbar"><button className="qm-menu-btn" onClick={()=>setOpen(true)} aria-label="Menyuni ochish"><Menu size={18}/></button><form className="qm-top-search" onSubmit={e=>{e.preventDefault();router.push("/admin/search?q="+encodeURIComponent(query.trim()));}}><button className="qm-top-search-submit" type="submit" aria-label="Admin qidiruvini boshlash"><Search size={16}/></button><input aria-label="Admin panelda qidirish" placeholder="E’lon, foydalanuvchi yoki kanalni qidiring..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="qm-top-search-submit" type="submit" aria-label="Qidirish"><kbd>↵</kbd></button></form><span className="qm-user"><span className="qm-avatar"><UserRound size={18}/></span><strong>Administrator</strong></span></header><main className="qm-content">{children}</main></div></div>;
}

