"use client";
import Link from "next/link";
import {RefreshCw,ArrowRight,ShieldCheck,ClipboardList,Send,CheckCircle2,TriangleAlert,FileClock} from "lucide-react";
import {Heading,Panel,Empty,Badge,dateOf} from "../components/qaytarme/ui";
import {useAdminData} from "../components/qaytarme/admin-api";
import {State,Stat,ItemsTable,auditNames} from "../components/qaytarme/AdminShared";
export default function Dashboard(){
 const {data,loading,error,refresh}=useAdminData("overview"),queue=useAdminData("items");
 const pending=(queue.data||[]).filter(x=>x.moderationStatus==="pending").slice(0,6);
 return <><Heading title="Dashboard" text="Platformadagi muhim ishlar va Telegram yig‘ish holati."><button className="qm-btn" onClick={()=>{refresh();queue.refresh();}}><RefreshCw size={14}/>Yangilash</button><Link className="qm-btn qm-btn-dark" href="/admin/moderation">Moderatsiyaga o‘tish <ArrowRight size={14}/></Link></Heading><State {...{loading,error,refresh}}/>
 <div className="qm-stats"><Stat title="Moderatsiya kutilmoqda" value={data?.pending} Icon={ShieldCheck} text="Tekshirish uchun navbatda"/><Stat title="Ochiq shikoyatlar" value={data?.openReports} Icon={TriangleAlert} text="Foydalanuvchilardan"/><Stat title="Jami e’lonlar" value={data?.total} Icon={ClipboardList} text="Barcha manbalardan"/><Stat title="Qaytarilgan buyumlar" value={data?.returned} Icon={CheckCircle2} text="Ikki tomon tasdiqlagan"/></div>
 <div className="qm-admin-grid"><Panel title="Moderatsiya navbati" actions={<Link href="/admin/moderation">Barcha navbatni ko‘rish →</Link>}><State loading={queue.loading} error={queue.error} refresh={queue.refresh}/><ItemsTable rows={pending} review/>{!pending.length&&!queue.loading&&<Empty title="Navbat bo‘sh" text="Yangi e’lonlar shu yerda tekshirishga keladi."/>}</Panel><div className="qm-admin-side"><Panel title="Tizim holati"><div className="qm-status-list"><div><span>Telegram userbot</span><Badge tone={data?.collector?.connected?"success":"warning"}>{data?.collector?.connected?"Ulangan":data?.collector?.configured?"Ulanmagan":"Sozlash kerak"}</Badge></div><div><span>Ulangan kanallar</span><strong>{data?.activeChannels??"—"} / {data?.channels??"—"}</strong></div><div><span>Telegram e’lonlari</span><strong>{data?.telegramItems??"—"}</strong></div><div><span>Takroriy e’lonlar</span><strong>{data?.duplicateItems??"—"}</strong></div><div><span>Oxirgi import</span><strong>{data?.collector?.lastImportAt?dateOf(data.collector.lastImportAt):"Hali bo‘lmagan"}</strong></div></div></Panel><Panel title="So‘nggi hodisalar" actions={<Link href="/admin/audit">Barchasi →</Link>}><div className="qm-activity">{data?.activity?.length?data.activity.map(a=><div className="qm-activity-row" key={a._id}><span className="qm-activity-icon"><FileClock size={13}/></span><div><strong>{auditNames[a.action]||a.action}</strong><small>#{a.entity.slice(-7)}</small></div><time>{dateOf(a.createdAt)}</time></div>):<Empty title="Hodisalar hali yo‘q"/>}</div></Panel></div></div>
 <div className="qm-help-strip"><Send size={21}/><div><strong>Telegram e’lonlari manbasi bilan saqlanadi</strong><p>Yangi kanalni ulang, so‘nggi postlarni import qiling va e’lonlarni tekshirib tasdiqlang.</p></div><Link href="/admin/telegram-channels">Manbalarni boshqarish <ArrowRight size={14}/></Link></div></>;
}

