"use client";
import {useEffect,useState} from "react";
import {useSession} from "next-auth/react";
import Link from "next/link";
import {UserRound,ShieldCheck,ClipboardList,CheckCircle2,Search} from "lucide-react";
import {Heading,Panel,Empty,Badge} from "../../components/qaytarme/ui";
import {Stat} from "../../components/qaytarme/AdminShared";
import {getApiUrl} from "@/lib/api-config";
export default function Profile(){
 const {data:session,status,update}=useSession(),[profile,setProfile]=useState(null),[form,setForm]=useState({name:"",phone:"",bio:""}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{if(!session?.user?.accessToken)return;const c=new AbortController();fetch(getApiUrl("users/me"),{signal:c.signal,headers:{Authorization:"Bearer "+session.user.accessToken}}).then(async r=>{if(!r.ok)throw Error("Profilni yuklab bo‘lmadi.");return r.json();}).then(p=>{setProfile(p);setForm({name:p.name||"",phone:p.phone||"",bio:p.bio||""});}).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return()=>c.abort();},[session]);
 async function save(e){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(getApiUrl("users/me"),{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.user.accessToken},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw Error(data.message||"Saqlab bo‘lmadi.");setMessage("Profil yangilandi.");await update({name:form.name});}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(status==="loading")return <div className="qm-loading">Yuklanmoqda…</div>;
 return <><Heading title="Profil" text="Shaxsiy ma’lumotlaringiz va xizmatdagi faoliyatingiz."/>{!session?<Panel><Empty title="Profilingizni ko‘rish uchun kiring"><Link className="qm-btn qm-btn-dark" href="/login?callbackUrl=%2Fdesktop%2Fprofile">Hisobga kirish</Link></Empty></Panel>:<>{error&&<div className="qm-notice qm-error" role="alert">{error}</div>}{message&&<div className="qm-notice" role="status">{message}</div>}<div className="qm-stats"><Stat title="Yo‘qotgan buyumlar" value={profile?.stats?.lostCount} Icon={Search}/><Stat title="Topgan buyumlar" value={profile?.stats?.foundCount} Icon={ClipboardList}/><Stat title="Qaytarilgan" value={profile?.stats?.returnedByMeCount} Icon={CheckCircle2}/><Stat title="Egamga qaytgan" value={profile?.stats?.returnedToMeCount} Icon={ShieldCheck}/></div><div className="qm-admin-grid"><Panel title="Shaxsiy ma’lumotlar"><form className="qm-form" onSubmit={save}><label><span>To‘liq ism *</span><input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Telefon raqami</span><input maxLength={30} type="tel" placeholder="+998" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span>O‘zingiz haqingizda</span><textarea maxLength={500} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><button className="qm-btn qm-btn-dark" disabled={busy||!profile}>{busy?"Saqlanmoqda…":"O‘zgarishlarni saqlash"}</button></form></Panel><Panel title="Hisob ma’lumotlari"><div className="qm-panel-body"><div className="qm-owner"><span className="qm-avatar"><UserRound size={23}/></span><div><strong>{profile?.name||session.user.name}</strong><small>{session.user.email}</small></div></div><Badge>{profile?.isVerified?"Email tasdiqlangan":"Email tasdiqlanmagan"}</Badge><div className="qm-notice" style={{marginTop:18}}>Aloqa ma’lumotlaringiz ochiq e’lonlar ro‘yxatida yashiriladi. Buyum egasi bilan platforma orqali bog‘laning.</div><Link className="qm-btn" href="/desktop/my-items">Mening e’lonlarim →</Link></div></Panel></div></>}</>;
}

