"use client";
import {useState,useEffect,Suspense} from "react";
import {useSearchParams} from "next/navigation";
import {Check,X,ChevronLeft,ChevronRight,Search,Info,MapPin,Calendar,ShieldCheck,Link2} from "lucide-react";
import {Heading,Panel,Empty,Badge,ItemImage,categoryLabel,dateOf} from "../../components/qaytarme/ui";
import {useAdminData,adminRequest} from "../../components/qaytarme/admin-api";
import {State,Notice,ModerationBadge} from "../../components/qaytarme/AdminShared";
const name=i=>i.itemType||i.itemName||"Buyum";
const sourceName=i=>i.provenance?.channelUsername?"@"+i.provenance.channelUsername.replace(/^@/,""):i.provenance?.sourceType==="telegram"?"Telegram":"Buyum Qidiruv";
const privateItem=i=>["docs","vehicle"].includes(i.category);
const duplicate=i=>i.cluster?.isPrimary===false||(i.cluster?.memberCount||1)>1;
const unclear=i=>!i.region||!i.occurredAt;
const tabMatch=(i,t)=>t==="all"||t==="unclear"&&unclear(i)||t==="privacy"&&privateItem(i)||t==="duplicate"&&duplicate(i);
function Moderation(){
 const {data,loading,error,refresh,token}=useAdminData("items"),params=useSearchParams();
 const [id,setId]=useState(params.get("id")||""),[q,setQ]=useState(""),[tab,setTab]=useState("all"),[status,setStatus]=useState("pending"),[source,setSource]=useState("all"),[region,setRegion]=useState("all"),[category,setCategory]=useState("all"),[onlyUnclear,setOnlyUnclear]=useState(false),[evidence,setEvidence]=useState("text"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[hideImages,setHideImages]=useState(true),[compare,setCompare]=useState(true);
 const all=data||[],base=all.filter(i=>status==="all"||i.moderationStatus===status);
 const rows=base.filter(i=>tabMatch(i,tab)&&(source==="all"||(source==="telegram"?i.provenance?.sourceType==="telegram":i.provenance?.sourceType!=="telegram"))&&(region==="all"||i.region===region)&&(category==="all"||i.category===category)&&(!onlyUnclear||unclear(i))&&[name(i),i.region,i.location,sourceName(i),i._id].join(" ").toLowerCase().includes(q.toLowerCase()));
 const item=rows.find(i=>i._id===id)||rows[0],index=rows.findIndex(i=>i._id===item?._id);
 useEffect(()=>{setNote("");setHideImages(true);},[item?._id]);
 useEffect(()=>{if(params.get("id")){setId(params.get("id"));setStatus("all");}},[params]);
 function choose(next){setId(next);setMessage("");}
 async function decide(next){if(!item||busy)return;if(!note.trim()){setMessage("Qaror uchun moderator izohini kiriting.");return;}setBusy(true);try{await adminRequest("items/"+item._id+"/decision",token,{status:next,note,hideImages});await refresh();setId("");setNote("");setMessage("Qaror saqlandi va audit jurnaliga yozildi.");}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const fields=item?[["Buyum nomi",name(item)],["Holat",item.status==="lost"?"Yo‘qolgan":"Topilgan"],["Kategoriya",categoryLabel(item.category)],["Hudud",item.region||"Noma’lum"],["Joylashuv",item.location||item.district||"Noma’lum"],["Sana",item.occurredAt?dateOf(item.occurredAt):item.date||"Noma’lum"]]:[];
 const visibleFields=fields.filter(f=>!onlyUnclear||f[1]==="Noma’lum");
 const raw=item?.provenance?.originalText||item?.itemDescription||"Matn mavjud emas";
 const related=item?.cluster?.clusterId?all.filter(i=>i._id!==item._id&&String(i.cluster?.clusterId)===String(item.cluster.clusterId)):[];
 return <div className="qm-moderation"><Heading title="Moderatsiya — AI tahlili" text="Ochiq manbadan ajratilgan ma’lumotlarni dalillar bilan tekshiring."><Badge>{all.filter(i=>i.moderationStatus==="pending").length} ta kutilmoqda</Badge><button className="qm-btn" aria-label="Oldingi e’lon" disabled={index<=0||busy} onClick={()=>choose(rows[index-1]._id)}><ChevronLeft size={14}/></button><button className="qm-btn" aria-label="Keyingi e’lon" disabled={index<0||index>=rows.length-1||busy} onClick={()=>choose(rows[index+1]._id)}><ChevronRight size={14}/></button></Heading>
 <State {...{loading,error,refresh}}/><Notice message={message}/>
 <div className="qm-mod-filters"><div className="qm-tabs">{[["all","Barchasi"],["unclear","Noaniq ma’lumot"],["privacy","Maxfiylik"],["duplicate","Takroriylik"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label} <span>{base.filter(i=>tabMatch(i,key)).length}</span></button>)}</div><label className="qm-mod-search"><Search size={13}/><input aria-label="E’lonlarni qidirish" placeholder="E’lonlarni qidirish..." value={q} onChange={e=>setQ(e.target.value)}/></label>
 <select aria-label="Moderatsiya holati" value={status} onChange={e=>setStatus(e.target.value)}>{[["pending","Kutilmoqda"],["approved","Tasdiqlangan"],["rejected","Rad etilgan"],["all","Barcha holatlar"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
 <select aria-label="Manba filtri" value={source} onChange={e=>setSource(e.target.value)}><option value="all">Manba: barchasi</option><option value="telegram">Telegram</option><option value="web">Foydalanuvchi</option></select>
 <select aria-label="Hudud filtri" value={region} onChange={e=>setRegion(e.target.value)}><option value="all">Hudud: barchasi</option>{[...new Set(all.map(i=>i.region).filter(Boolean))].sort().map(r=><option key={r}>{r}</option>)}</select>
 <select aria-label="Kategoriya filtri" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Kategoriya: barchasi</option>{[...new Set(all.map(i=>i.category).filter(Boolean))].map(c=><option key={c} value={c}>{categoryLabel(c)}</option>)}</select>
 <label className="qm-mod-toggle"><input type="checkbox" checked={onlyUnclear} onChange={e=>setOnlyUnclear(e.target.checked)}/>Faqat noaniq maydonlar</label></div>
 <div className="qm-mod-grid"><Panel title="Tekshiruv navbati" className="qm-mod-queue-panel" actions={<small>{rows.length} ta</small>}><div className="qm-mod-queue">{rows.map(i=><button key={i._id} className={item?._id===i._id?"active":""} disabled={busy} onClick={()=>choose(i._id)}><ItemImage item={i}/><span><strong>{name(i)}</strong><small>{sourceName(i)}</small><small>{dateOf(i.createdAt)}</small><em>{privateItem(i)?"Maxfiylik tekshiruvi":duplicate(i)?"Takroriy post":unclear(i)?"Ma’lumot noaniq":"Tekshirish kerak"}</em></span></button>)}</div>{!rows.length&&!loading&&<Empty title="Navbat bo‘sh" text="Boshqa filtrni tanlang."/>}<div className="qm-mod-queue-footer"><span>{rows.length?index+1:0} / {rows.length}</span><button className="qm-btn" onClick={refresh} disabled={busy||loading}>Yangilash</button></div></Panel>
 <Panel className="qm-mod-evidence">{item?<><div className="qm-mod-event"><div><h2>Hodisa #EVT-{item._id.slice(-6).toUpperCase()}</h2><small>Birinchi kuzatilgan: {dateOf(item.cluster?.firstSeenAt||item.createdAt)}</small></div><ModerationBadge value={item.moderationStatus}/></div>
 <div className="qm-mod-posts"><article className="qm-mod-post"><header><strong>{item.provenance?.sourceType==="telegram"?"Asl Telegram posti":"Asl e’lon"}</strong><small>#{item.provenance?.messageIds?.[0]||item._id.slice(-6)}</small></header><ItemImage item={item}/><div className="qm-mod-post-meta"><span>{sourceName(item)}</span><small>{dateOf(item.provenance?.publishedAt||item.createdAt)}</small></div><p className="qm-mod-raw">{raw}</p>{!item.provenance?.originalText&&item.provenance?.sourceType==="telegram"&&<small>Asl matn saqlanmagan; e’lon tavsifi ko‘rsatilmoqda.</small>}{item.provenance?.sourceUrl&&<a className="qm-inline-link" href={item.provenance.sourceUrl} target="_blank" rel="noreferrer">Manbani ochish ↗</a>}</article>
 <article className="qm-mod-post"><header><strong>Tizim yaratgan e’lon</strong><label><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/>Taqqoslash</label></header><div className="qm-mod-generated"><Badge>{item.status==="lost"?"YO‘QOLGAN":"TOPILGAN"}</Badge><h2>{name(item)}</h2><ItemImage item={item}/><p>{categoryLabel(item.category)}</p><p><MapPin size={12}/>{item.location||item.region||"Joy noma’lum"}</p><p><Calendar size={12}/>{item.date||dateOf(item.createdAt)}</p>{compare&&<p>{item.itemDescription||"Tavsif mavjud emas"}</p>}</div></article></div>
 <div className="qm-mod-tabs"><strong>Dalillar</strong>{[["text","Matn"],["image","Rasm"],["sources","Manbalar"],["timeline","Vaqt chizig‘i"]].map(([key,label])=><button key={key} className={evidence===key?"active":""} onClick={()=>setEvidence(key)}>{label}</button>)}</div>
 {evidence==="text"&&<div className="qm-table-wrap"><table className="qm-table qm-mod-table"><thead><tr><th>Ajratilgan qiymat</th><th>Maydon</th><th>Manba matnidagi dalil</th></tr></thead><tbody>{visibleFields.map(([label,value])=><tr key={label}><td><strong>{value}</strong></td><td>{label}</td><td>{value!=="Noma’lum"&&raw.toLowerCase().includes(value.toLowerCase())?<q>{value}</q>:"To‘g‘ridan-to‘g‘ri dalil belgilanmagan"}</td></tr>)}</tbody></table></div>}
 {evidence==="image"&&<div className="qm-mod-image-evidence"><ItemImage item={item}/><p>Asl manba rasmi. Maxfiy ma’lumotlarni tekshiring.</p></div>}
 {evidence==="sources"&&<div className="qm-mod-tab-content"><p>{sourceName(item)}</p>{item.provenance?.sourceUrl?<a href={item.provenance.sourceUrl} target="_blank" rel="noreferrer" className="qm-inline-link">Asl postni ko‘rish ↗</a>:<p>Foydalanuvchi platformada joylashtirgan.</p>}<p>Parser: {item.provenance?.parserVersion||"Ma’lumot yo‘q"}</p><p>{item.cluster?.sourceCount||1} ta manba · {item.cluster?.memberCount||1} ta post</p></div>}
 {evidence==="timeline"&&<div className="qm-mod-tab-content">{[["Manbada e’lon qilingan",item.provenance?.publishedAt],["Yig‘ib olingan",item.provenance?.collectedAt||item.createdAt],["Oxirgi kuzatilgan",item.cluster?.lastSeenAt||item.updatedAt]].map(([label,date])=><p key={label}>{label}: {date?dateOf(date):"Ma’lumot yo‘q"}</p>)}</div>}
 <div className="qm-mod-related"><h3><Link2 size={13}/>Takroriy postlar <Badge>{related.length}</Badge></h3>{related.length?<div className="qm-table-wrap"><table className="qm-table qm-mod-table"><thead><tr><th>Manba</th><th>Vaqt</th><th>E’lon</th><th>Amal</th></tr></thead><tbody>{related.map(r=><tr key={r._id}><td>{sourceName(r)}</td><td>{dateOf(r.createdAt)}</td><td>{name(r)}</td><td><a href={"/admin/moderation?id="+r._id}>Ko‘rish ↗</a></td></tr>)}</tbody></table></div>:<p>Ushbu hodisaga birlashtirilgan boshqa post topilmadi.</p>}</div></>:<Empty title="Tekshiriladigan e’lon yo‘q" text="Filtrlarni o‘zgartiring."/>}</Panel>
 <Panel title="AI ajratgan maydonlar" className="qm-mod-analysis" actions={<small>Ishonchlilik: —</small>}>{item?<><div className="qm-mod-ai-note"><Info size={13}/>AI foizlari hozircha saqlanmagan. Tizimdagi haqiqiy qiymatlar ko‘rsatilgan.</div><div className="qm-table-wrap"><table className="qm-table qm-mod-table"><thead><tr><th>Maydon</th><th>Qiymat</th><th>Dalil</th></tr></thead><tbody>{visibleFields.map(([label,value])=><tr key={label}><td>{label}</td><td><strong>{value}</strong></td><td><button className="qm-mod-evidence-link" onClick={()=>setEvidence("text")}>Ko‘rish</button></td></tr>)}</tbody></table></div>
 <div className="qm-mod-checks"><h3><ShieldCheck size={13}/>Tekshiruv natijalari</h3>{[["Takroriylik",duplicate(item)?"Birlashtirilgan postlar mavjud":"Takroriy post belgilanmagan"],["Maxfiylik",privateItem(item)?"Hujjat / raqamni tekshirish kerak":"Moderator tekshiruvi kerak"],["Manba",sourceName(item)],["Geografik aniqlik",item.coordinates?"Koordinatalar mavjud":item.region?"Hudud darajasida":"Hudud noaniq"],["Sana",item.occurredAt?"Sana aniqlangan":"Aniq sana saqlanmagan"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <div className="qm-mod-reasons"><h3><Info size={13}/>Nega tekshirish kerak?</h3><ul>{privateItem(item)&&<li>Rasmda shaxsiy hujjat yoki avtomobil raqami bo‘lishi mumkin.</li>}{!item.region&&<li>Hudud aniqlanmagan.</li>}{!item.occurredAt&&<li>Hodisa sanasi aniqlanmagan.</li>}{duplicate(item)&&<li>Takroriy postlar mavjud.</li>}<li>Manba va ajratilgan ma’lumotlar moderator tasdig‘ini talab qiladi.</li></ul></div></>:<Empty title="Tahlil uchun e’lon tanlang"/>}</Panel></div>
 {item&&<div className="qm-mod-decision"><label className="qm-mod-note">Moderator izohi *<textarea maxLength={1000} aria-label="Moderator izohi" placeholder="Qaroringizni izohlang..." value={note} onChange={e=>setNote(e.target.value)}/></label><div className="qm-mod-decision-actions"><div><button className="qm-btn" disabled={busy||item.moderationStatus==="returned"} onClick={()=>decide("pending")}>Qayta tekshirish</button><button className="qm-btn qm-btn-danger" disabled={busy||item.moderationStatus==="returned"} onClick={()=>decide("rejected")}><X size={13}/>Rad etish</button><button className="qm-btn qm-btn-dark" disabled={busy||item.moderationStatus==="returned"} onClick={()=>decide("approved")}><Check size={13}/>{busy?"Saqlanmoqda…":"Tasdiqlash"}</button></div><label><input type="checkbox" checked={hideImages} onChange={e=>setHideImages(e.target.checked)}/>Rasmlarni ochiq ko‘rinishdan yashirish</label><small><Info size={11}/>Qaror va izoh audit jurnaliga yoziladi.</small></div></div>}
 </div>;
}
export default function Page(){return <Suspense fallback={<div className="qm-loading">Yuklanmoqda…</div>}><Moderation/></Suspense>;}

