"use client";
import {useState} from "react";
import Link from "next/link";
import {RefreshCw,TriangleAlert,Eye} from "lucide-react";
import {Heading,Panel,Empty,Badge,dateOf} from "../../components/qaytarme/ui";
import {useAdminData,adminRequest} from "../../components/qaytarme/admin-api";
import {State,Notice,reasons,labels} from "../../components/qaytarme/AdminShared";
export default function Reports(){
 const {data,loading,error,refresh,token}=useAdminData("reports"),[tab,setTab]=useState("open"),[id,setId]=useState(""),[note,setNote]=useState(""),[hide,setHide]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const rows=(data||[]).filter(i=>tab==="all"||i.status===tab),item=rows.find(i=>i._id===id)||rows[0];
 async function resolve(status){if(!note.trim()){setMessage("Qaror izohini kiriting.");return;}setBusy(true);try{await adminRequest("reports/"+item._id+"/resolve",token,{status,note,hideItem:hide});setMessage("Shikoyat bo‘yicha qaror saqlandi.");setNote("");setHide(false);await refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <><Heading title="Shikoyatlar" text="Foydalanuvchi shikoyatlarini tekshiring va asoslangan qaror qabul qiling."><button className="qm-btn" onClick={refresh}><RefreshCw size={14}/>Navbatni yangilash</button></Heading><State {...{loading,error,refresh}}/><Notice message={message}/><div className="qm-tabs" style={{marginBottom:18}}>{["open","resolved","dismissed","all"].map(k=><button key={k} onClick={()=>{setTab(k);setId("");}} className={tab===k?"active":""}>{k==="all"?"Barchasi":labels[k]}</button>)}</div><div className="qm-split"><Panel title="Shikoyatlar navbati"><div className="qm-queue">{rows.map(r=><button key={r._id} onClick={()=>{setId(r._id);setNote("");setHide(false);}} className={item?._id===r._id?"active":""}><TriangleAlert size={24}/><div><strong>{reasons[r.reason]||r.reason}</strong><small>{dateOf(r.createdAt)} · {labels[r.status]}</small></div></button>)}</div>{!loading&&!rows.length&&<Empty title="Shikoyatlar yo‘q"/>}</Panel><Panel title="Shikoyatni ko‘rib chiqish">{item?<div className="qm-review"><Badge>{labels[item.status]}</Badge><h2>{reasons[item.reason]||item.reason}</h2><p>{item.description||"Qo‘shimcha izoh kiritilmagan."}</p><Link target="_blank" href={"/desktop/item/"+item.itemId} className="qm-btn"><Eye size={14}/>E’lonni ko‘rish</Link><dl className="qm-definition"><div><dt>E’lon ID</dt><dd>{item.itemId}</dd></div><div><dt>Yuborilgan</dt><dd>{dateOf(item.createdAt)}</dd></div>{item.resolution&&<div><dt>Qaror</dt><dd>{item.resolution}</dd></div>}</dl>{item.status==="open"&&<><label className="qm-notice" style={{display:"flex",gap:8}}><input type="checkbox" checked={hide} onChange={e=>setHide(e.target.checked)}/>E’lonni qayta moderatsiyaga yuborish</label><div className="qm-action-bar"><textarea aria-label="Qaror izohi" placeholder="Qaror uchun izoh..." value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/><button className="qm-btn" disabled={busy} onClick={()=>resolve("dismissed")}>Asossiz deb yopish</button><button className="qm-btn qm-btn-dark" disabled={busy} onClick={()=>resolve("resolved")}>Hal qilingan deb belgilash</button></div></>}</div>:<Empty title="Shikoyat tanlanmagan"/>}</Panel></div></>;
}

