"use client";
import {useState,useMemo,useCallback} from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import {Search,MapPin,Send,Info,ArrowRight,Plus,Minus,Maximize2,X,SlidersHorizontal} from "lucide-react";
import {Empty,categoryLabel,categories} from "../../components/qaytarme/ui";
import {buildRegionalAnalysis} from "./regional-analysis.mjs";
const RegionalMap=dynamic(()=>import("./RegionalMap"),{ssr:false,loading:()=> <div className="qm-loading">Xarita yuklanmoqda…</div>});
export default function RegionalAnalysis({items,loading,error,onRetry}){
 const [days,setDays]=useState("30"),[status,setStatus]=useState("all"),[category,setCategory]=useState("all"),[source,setSource]=useState("all"),[query,setQuery]=useState(""),[metric,setMetric]=useState("count"),[layer,setLayer]=useState("density"),[selectedKey,setSelectedKey]=useState(""),[sort,setSort]=useState("count"),[map,setMap]=useState(null);
 const analysis=useMemo(()=>buildRegionalAnalysis(items,{days,status,category,source,query}),[items,days,status,category,source,query]);
 const areas=useMemo(()=>[...analysis.areas].sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="sources"?b.channels.length-a.channels.length:b.count-a.count),[analysis,sort]);
 const selected=areas.find(a=>a.key===selectedKey)||null;
 const ready=useCallback(m=>setMap(m),[]);
 function fit(){const centers=areas.filter(a=>a.center&&!a.suppressed).map(a=>a.center);if(map&&centers.length)map.fitBounds(centers,{padding:[45,45],maxZoom:11});}
 function reset(){setDays("30");setStatus("all");setCategory("all");setSource("all");setQuery("");setMetric("count");setSelectedKey("");}
 return <div className="qm-regional"><div className="qm-regional-toolbar"><label className="qm-regional-search"><Search size={15}/><input aria-label="Hududni qidirish" placeholder="Hudud bo‘yicha qidiring..." value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <select aria-label="Tahlil davri" value={days} onChange={e=>setDays(e.target.value)}><option value="7">Davr: 7 kun</option><option value="30">Davr: 30 kun</option><option value="90">Davr: 90 kun</option><option value="all">Barcha davr</option></select>
 <select aria-label="Hodisa turi" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Hodisa: barchasi</option><option value="lost">Yo‘qolgan</option><option value="found">Topilgan</option></select>
 <select aria-label="Tahlil kategoriyasi" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([key,label])=><option key={key} value={key}>{key==="all"?"Kategoriya: barchasi":label}</option>)}</select>
 <select aria-label="Tahlil manbasi" value={source} onChange={e=>setSource(e.target.value)}><option value="all">Manba: barchasi</option><option value="telegram">Telegram</option><option value="web">Saytdagi e’lonlar</option></select>
 <select aria-label="Tahlil ko‘rsatkichi" value={metric} onChange={e=>setMetric(e.target.value)}><option value="count">Ko‘rsatkich: e’lonlar</option><option value="lost">Yo‘qolgan buyumlar</option><option value="found">Topilgan buyumlar</option></select>
 <button className="qm-btn" onClick={reset}><SlidersHorizontal size={13}/>Tozalash</button></div>
 {error&&<div role="alert" className="qm-notice qm-error">{error}<button className="qm-btn" onClick={onRetry}>Qayta urinish</button></div>}
 <div className="qm-regional-grid"><aside className="qm-regional-list"><header><div><h2><MapPin size={16}/>Hududlar</h2><small>{loading?"Yuklanmoqda…":areas.length+" ta hudud bo‘yicha tahlil"}</small></div><select aria-label="Hududlarni saralash" value={sort} onChange={e=>setSort(e.target.value)}><option value="count">Eng ko‘p e’lon</option><option value="sources">Eng ko‘p manba</option><option value="name">Nom bo‘yicha</option></select></header>
 <div className="qm-regional-results">{areas.map((area,i)=><button key={area.key} className={selected?.key===area.key?"active":""} onClick={()=>setSelectedKey(area.key)}><span className="qm-regional-rank">{i+1}</span><span className="qm-regional-area"><strong>{area.name}</strong><small>{area.district?area.region:"Viloyat / shahar darajasida"}</small><em>{area.suppressed?"Statistika yashirilgan":area.channels.length?"Manba mavjud":"Manba aniqlanmagan"}</em>{!area.suppressed&&<><small>Asosiy kategoriya: {categoryLabel(area.categories[0]?.[0])}</small><small><Send size={11}/>{area.channels.length} ta kanal e’lonlarda uchragan</small></>}</span><span className="qm-regional-count"><strong>{area.suppressed?"—":area[metric]}</strong><small>e’lon</small><ArrowRight size={13}/></span></button>)}{!loading&&!areas.length&&<Empty title="Hudud topilmadi" text="Davrni kengaytiring yoki filtrlarni tozalang."/>}</div>
 <div className="qm-regional-privacy"><Info size={14}/><span>{analysis.suppressed} ta hududda e’lonlar soni 5 tadan kam. Statistikasi yashirilgan.</span></div></aside>
 <section className="qm-regional-canvas"><RegionalMap areas={areas} selected={selected} onSelect={setSelectedKey} onMapReady={ready} layer={layer} metric={metric}/>
 <div className="qm-regional-layers"><strong>Xarita qatlami</strong>{[["density","E’lonlar zichligi"],["source","Telegram manbalari"],["missing","Manba aniqlanmagan hududlar"]].map(([value,label])=><label key={value}><input type="radio" name="regional-layer" checked={layer===value} onChange={()=>setLayer(value)}/>{label}</label>)}</div>
 <div className="qm-regional-controls"><button aria-label="Tahlil xaritasini yaqinlashtirish" onClick={()=>map?.zoomIn()}><Plus size={16}/></button><button aria-label="Tahlil xaritasini uzoqlashtirish" onClick={()=>map?.zoomOut()}><Minus size={16}/></button><button aria-label="Barcha hududlarni ko‘rish" onClick={fit}><Maximize2 size={16}/></button></div>
 {selected&&<article className="qm-regional-detail"><button className="qm-regional-close" aria-label="Hudud tafsilotini yopish" onClick={()=>setSelectedKey("")}><X size={14}/></button><h3>{selected.name}</h3><p><MapPin size={11}/>{selected.region||"Hudud"} · {selected.center?"Taxminiy joylashuv":"Koordinatalar mavjud emas"}</p>
 {selected.suppressed?<div className="qm-regional-detail-empty"><Info size={18}/><p>Bu hududda 5 tadan kam e’lon bor. Batafsil statistika ko‘rsatilmaydi.</p></div>:<><div className="qm-regional-totals">{[["Jami e’lon",selected.count],["Yo‘qolgan",selected.lost],["Topilgan",selected.found]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><h4>Asosiy kategoriyalar</h4>{selected.categories.slice(0,3).map(([key,count])=><div className="qm-regional-category" key={key}><span>{categoryLabel(key)}</span><i><b style={{width:Math.round(count/selected.count*100)+"%"}}/></i><strong>{count}</strong></div>)}<div className="qm-regional-detail-row"><Send size={13}/><span>E’lonlarda uchragan kanallar</span><strong>{selected.channels.length}</strong></div><div className="qm-regional-detail-row"><span>Oldingi davrga nisbatan</span><strong>{selected.trend==null?"Ma’lumot yetarli emas":(selected.trend>0?"+":"")+selected.trend+"%"}</strong></div><Link className="qm-btn qm-btn-dark" href={"/desktop/listings?q="+encodeURIComponent(selected.district||selected.region)}>Hudud e’lonlarini ko‘rish <ArrowRight size={13}/></Link></>}</article>}
 {!loading&&!selected&&!areas.some(a=>a.center&&!a.suppressed)&&<div className="qm-regional-map-empty"><Info size={16}/>Xaritada ko‘rsatishga yetarli ma’lumot yo‘q. Hududlar ro‘yxatidan tanlashingiz mumkin.</div>}
 <div className="qm-regional-legend"><span>Kam e’lon</span>{["#e7e7e9","#c8c9cd","#9fa1a7","#74767f","#42444d"].map(color=><i key={color} style={{background:color}}/>)}<span>Ko‘p e’lon</span></div></section></div>
 <footer className="qm-regional-footer"><div><Send size={17}/><span><strong>Manba qamrovi: {analysis.withSources}/{areas.length} hudud</strong><small>Faqat e’lonlarda uchragan Telegram kanallari hisoblangan.</small></span></div><div><Info size={17}/><span><strong>{analysis.unknown} ta e’londa hudud noma’lum · {analysis.unlocated} ta hududda koordinata yo‘q</strong><small>Hudud markazlari taxminiy; rasmiy ma’muriy chegaralar ko‘rsatilmagan.</small></span></div></footer>
 </div>;
}
