"use client";
import {useState} from "react";
import Link from "next/link";
import {Send,Play,Pause,ShieldCheck,Plus,RefreshCw,ExternalLink} from "lucide-react";
import {Heading,Panel,Empty,Badge,dateOf} from "../../components/qaytarme/ui";
import {useAdminData,adminRequest} from "../../components/qaytarme/admin-api";
import {State,Notice,Stat} from "../../components/qaytarme/AdminShared";
export default function Channels(){
 const {data,loading,error,refresh,token}=useAdminData("channels"),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[form,setForm]=useState(false),[username,setUsername]=useState(""),[description,setDescription]=useState(""),[region,setRegion]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const overview=useAdminData("overview"),rows=(data||[]).filter(c=>[c.username,c.description,c.region].join(" ").toLowerCase().includes(q.toLowerCase()));
 async function add(e){e.preventDefault();setBusy(true);try{await adminRequest("channels",token,{username,description,region});setForm(false);setUsername("");setDescription("");setRegion("");setMessage("Kanal qo‘shildi. Userbot ulangan bo‘lsa, kuzatuv boshlanadi.");await refresh();overview.refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function toggle(c){setBusy(true);try{await adminRequest("channels/"+c._id,token,{isActive:!c.isActive},"PATCH");setMessage(c.isActive?"Kanal vaqtincha to‘xtatildi.":"Kanal faollashtirildi.");await refresh();overview.refresh();setSelected(null);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function importPosts(c){setBusy(true);setMessage("So‘nggi 30 ta post tekshirilmoqda…");try{const r=await adminRequest("channels/"+c._id+"/import",token,{});setMessage(r.checked+" ta post tekshirildi. "+r.processed+" ta e’lon guruhi tahlil qilindi; takroriy postlar qayta yaratilmaydi.");await refresh();overview.refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <><Heading title="Telegram manbalari" text="E’lonlar yig‘iladigan ochiq Telegram kanallarini ulang va boshqaring."><button className="qm-btn qm-btn-dark" onClick={()=>{setForm(!form);setSelected(null);}}><Plus size={14}/>Kanal qo‘shish</button></Heading><div className="qm-stats"><Stat title="Ulangan" value={data?.length} Icon={Send} text="Ro‘yxatdagi kanallar"/><Stat title="Faol" value={data?.filter(c=>c.isActive).length} Icon={Play} text="Kuzatuv yoqilgan"/><Stat title="To‘xtatilgan" value={data?.filter(c=>!c.isActive).length} Icon={Pause} text="Kuzatuv pauzada"/><Stat title="Userbot" value={overview.data?.collector?.connected?"Ulangan":"Ulanmagan"} Icon={ShieldCheck} text={overview.data?.collector?.configured?"Session sozlangan":"Session sozlash kerak"}/></div><State {...{loading,error,refresh}}/><Notice message={message}/>{!overview.data?.collector?.connected&&<div className="qm-notice">Telegram yig‘uvchi hozir ulanmagan. Kanallar ro‘yxatini tayyorlashingiz mumkin; import uchun serverda Telegram session sozlanishi kerak.</div>}
 <div className={form||selected?"qm-admin-grid":""}><Panel title="Ulangan kanallar"><div className="qm-toolbar"><input aria-label="Kanallarni qidirish" placeholder="Kanal nomi yoki @username" value={q} onChange={e=>setQ(e.target.value)}/><button className="qm-btn" onClick={refresh}><RefreshCw size={13}/>Yangilash</button></div><div className="qm-table-wrap"><table className="qm-table"><thead><tr><th>Kanal</th><th>Hudud</th><th>Holat</th><th>Import</th><th>Amallar</th></tr></thead><tbody>{rows.map(c=><tr key={c._id}><td><strong>@{c.username}</strong><small>{c.description||"Ochiq Telegram kanal"}</small></td><td>{c.region||"Ko‘rsatilmagan"}</td><td><Badge tone={c.lastError?"warning":c.isActive?"success":""}>{c.lastError?"Ulanish xatosi":c.isActive?"Faol":"To‘xtatilgan"}</Badge></td><td>{c.imported||0}<small>{c.lastImportedAt?dateOf(c.lastImportedAt):"Hali import qilinmagan"}</small></td><td><div className="qm-table-actions"><Link className="qm-btn" href={"/admin/telegram-channels/"+c._id}>Ko‘rish</Link><button className="qm-icon-btn" disabled={busy} aria-label={c.isActive?"Kanalni to‘xtatish":"Kanalni faollashtirish"} onClick={()=>toggle(c)}>{c.isActive?<Pause size={13}/>:<Play size={13}/>}</button></div></td></tr>)}</tbody></table></div>{!rows.length&&!loading&&<Empty title="Kanal hali ulanmagan" text="E’lonlar beriladigan Telegram kanalini qo‘shing."/>}</Panel>
 {form?<Panel title="Kanal qo‘shish"><form className="qm-form" onSubmit={add}><label><span>Telegram kanal username *</span><input required pattern="@?[a-zA-Z][a-zA-Z0-9_]{4,31}" placeholder="@kanal_username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label><span>Qisqa tavsif</span><textarea maxLength={300} placeholder="Yo‘qolgan va topilgan buyumlar haqida e’lonlar" value={description} onChange={e=>setDescription(e.target.value)}/></label><label><span>Hudud</span><input maxLength={80} placeholder="Masalan: Toshkent" value={region} onChange={e=>setRegion(e.target.value)}/></label><p className="qm-notice">Kanal qo‘shilgach, userbot uning ochiq postlarini kuzatadi. Maxfiy Telegram kalitlari serverdagi muhit faylida saqlanadi.</p><button disabled={busy} className="qm-btn qm-btn-dark">{busy?"Qo‘shilmoqda…":"Kanalni ulash"}</button><button type="button" className="qm-btn" onClick={()=>setForm(false)}>Bekor qilish</button></form></Panel>:selected?<Panel title="Manba tafsilotlari"><div className="qm-review"><Badge>{selected.isActive?"Faol manba":"To‘xtatilgan"}</Badge><h2>@{selected.username}</h2><p>{selected.description}</p><a href={"https://t.me/"+selected.username} target="_blank" rel="noreferrer" className="qm-btn"><ExternalLink size={13}/>Kanalni ochish</a><dl className="qm-definition"><div><dt>Hudud</dt><dd>{selected.region||"Ko‘rsatilmagan"}</dd></div><div><dt>Jami import</dt><dd>{selected.imported||0} ta e’lon</dd></div><div><dt>Oxirgi tekshiruv</dt><dd>{selected.lastCheckedAt?dateOf(selected.lastCheckedAt):"Hali tekshirilmagan"}</dd></div><div><dt>Ulanish xatosi</dt><dd>{selected.lastError||"Qayd etilmagan"}</dd></div></dl><div className="qm-action-bar"><button className="qm-btn" disabled={busy} onClick={()=>toggle(selected)}>{selected.isActive?"Vaqtincha to‘xtatish":"Faollashtirish"}</button><button className="qm-btn qm-btn-dark" disabled={busy||!selected.isActive||!overview.data?.collector?.connected} onClick={()=>importPosts(selected)}><Play size={14}/>Sinov importi</button></div></div></Panel>:null}</div></>;
}

