"use client";
import {useState} from "react";
import {Download,Eye} from "lucide-react";
import {Heading,Panel,Empty,Badge,dateOf} from "../../components/qaytarme/ui";
import {useAdminData,downloadJson} from "../../components/qaytarme/admin-api";
import {State,auditNames} from "../../components/qaytarme/AdminShared";
export default function Audit(){
 const {data,loading,error,refresh}=useAdminData("audit"),[q,setQ]=useState(""),[type,setType]=useState("all"),[id,setId]=useState("");
 const rows=(data||[]).filter(a=>(type==="all"||a.action===type)&&[a.actor,a.entity,a.action].join(" ").toLowerCase().includes(q.toLowerCase())),item=rows.find(a=>a._id===id);
 return <><Heading title="Audit jurnali" text="Administrator, moderator va foydalanuvchi amallarining serverda saqlangan tarixi."><button className="qm-btn" onClick={()=>downloadJson(rows,"qaytarme-audit")}><Download size={14}/>Eksport</button></Heading><State {...{loading,error,refresh}}/><div className={item?"qm-admin-grid":""}><Panel><div className="qm-toolbar"><input aria-label="Auditni qidirish" placeholder="Amal, bajaruvchi yoki obyekt ID" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Amal turi" value={type} onChange={e=>setType(e.target.value)}><option value="all">Barcha amallar</option>{Object.entries(auditNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="qm-table-wrap"><table className="qm-table"><thead><tr><th>Vaqt</th><th>Amal</th><th>Bajaruvchi</th><th>Obyekt</th><th>Tafsilot</th></tr></thead><tbody>{rows.map(a=><tr key={a._id} className={id===a._id?"selected":""}><td>{dateOf(a.createdAt)}<small>{new Date(a.createdAt).toLocaleTimeString("uz-UZ",{timeZone:"Asia/Tashkent",hour:"2-digit",minute:"2-digit"})}</small></td><td><strong>{auditNames[a.action]||a.action}</strong></td><td>#{a.actor.slice(-7)}</td><td>#{a.entity.slice(-7)}</td><td><button className="qm-icon-btn" aria-label="Hodisa tafsilotlarini ko‘rish" onClick={()=>setId(a._id)}><Eye size={14}/></button></td></tr>)}</tbody></table></div>{!rows.length&&!loading&&<Empty title="Hodisalar topilmadi"/>}</Panel>{item&&<Panel title="Hodisa tafsilotlari"><div className="qm-review"><Badge>Server yozuvi</Badge><h2>{auditNames[item.action]||item.action}</h2><dl className="qm-definition"><div><dt>Bajaruvchi ID</dt><dd>{item.actor}</dd></div><div><dt>Obyekt</dt><dd>{item.entity}</dd></div>{Object.entries(item.details||{}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><button className="qm-btn" onClick={()=>setId("")}>Yopish</button></div></Panel>}</div><div className="qm-notice" style={{marginTop:18}}>Jurnal yozuvlarini bu panel orqali tahrirlash yoki o‘chirish mumkin emas. Oxirgi 500 ta hodisa ko‘rsatiladi.</div></>;
}

